notifications:
  email:
    recipients:
      - gilles-travis@noekeon.org
    on_success: always
    on_failure: always

language: c

sudo: required

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -qq update && sudo apt-get install xsltproc; fi  

jobs:
  allow_failures:
    - script: make generic64/UnitTests && bin/generic64/UnitTests -a
      arch: arm64
      compiler: clang
    - script: make ARMv8A/UnitTests && bin/ARMv8A/UnitTests -a
      arch: arm64
  include:
    - stage: "Tests on ARM64 (linux)"
      script: make generic64/UnitTests && bin/generic64/UnitTests -a
      os: linux
      arch: arm64
      compiler: gcc
      name: "generic64 (gcc)"
    - script: make generic64/UnitTests && bin/generic64/UnitTests -a
      os: linux
      arch: arm64
      compiler: clang
      name: "generic64 (clang)"
    - script: make ARMv8A/UnitTests && bin/ARMv8A/UnitTests -a
      os: linux
      arch: arm64
      compiler: gcc
      name: "ARMv8A (gcc)"
    - script: make ARMv8A/UnitTests && bin/ARMv8A/UnitTests -a
      os: linux
      arch: arm64
      compiler: clang
      name: "ARMv8A (clang)"

    - stage: "Tests on AMD64 (linux)"
      script: make generic64/UnitTests && bin/generic64/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "generic64 (gcc)"
    - script: make generic64/UnitTests && bin/generic64/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "generic64 (clang)"
    - script: make asmX86-64/UnitTests && bin/asmX86-64/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "asmX86-64 (gcc)"
    - script: make asmX86-64shld/UnitTests && bin/asmX86-64shld/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "asmX86-64shld (gcc)"
    - script: make Nehalem/UnitTests && bin/Nehalem/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "Nehalem (gcc)"
    - script: make Nehalem/UnitTests && bin/Nehalem/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "Nehalem (clang)"
    - script: make SandyBridge/UnitTests && bin/SandyBridge/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "SandyBridge (gcc)"
    - script: make SandyBridge/UnitTests && bin/SandyBridge/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "SandyBridge (clang)"
    - script: make Haswell/UnitTests && bin/Haswell/UnitTests -a
      os: linux
      arch: amd64
      compiler: gcc
      name: "Haswell (gcc)"
    - script: make Haswell/UnitTests && bin/Haswell/UnitTests -a
      os: linux
      arch: amd64
      compiler: clang
      name: "Haswell (clang)"
 
    - stage: "Tests on AMD64 (osx)"
      script: make generic64/UnitTests && bin/generic64/UnitTests -a
      os: osx
      arch: amd64
      compiler: gcc
      name: "generic64 (gcc)"
    - script: make generic64/UnitTests && bin/generic64/UnitTests -a
      os: osx
      arch: amd64
      compiler: clang
      name: "generic64 (clang)"
    - script: make Nehalem/UnitTests && bin/Nehalem/UnitTests -a
      os: osx
      arch: amd64
      compiler: gcc
      name: "Nehalem (gcc)"
    - script: make Nehalem/UnitTests && bin/Nehalem/UnitTests -a
      os: osx
      arch: amd64
      compiler: clang
      name: "Nehalem (clang)"
    - script: make SandyBridge/UnitTests && bin/SandyBridge/UnitTests -a
      os: osx
      arch: amd64
      compiler: gcc
      name: "SandyBridge (gcc)"
    - script: make SandyBridge/UnitTests && bin/SandyBridge/UnitTests -a
      os: osx
      arch: amd64
      compiler: clang
      name: "SandyBridge (clang)"
